=== jean-andre-gauthier/xmlschema.js/test/pokemons/xsd/pokemon.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="https://paulwardrip.github.io/xmlschema.js/demo/pokemon"
    xmlns:stats="https://paulwardrip.github.io/xmlschema.js/demo/pokemon/stats">

    <xs:include schemaLocation="pokemon-common.xsd"/>

    <xs:import namespace="https://paulwardrip.github.io/xmlschema.js/demo/pokemon/stats" schemaLocation="pokemon-stats.xsd" />

    <xs:element name="trainer" type="Trainer">
        <xs:unique name="PokemonID">
            <xs:selector xpath="//pokemon" />
            <xs:field xpath="@id" />
        </xs:unique>
    </xs:element>

    <xs:attributeGroup name="PokemonAttributes">
        <xs:attribute name="level" use="required" />
        <xs:attribute name="hp" use="required" />
    </xs:attributeGroup>

    <xs:complexType name="ItemType">
        <xs:attribute name="inventory" use="required" />
    </xs:complexType>

    <xs:complexType name="Trainer">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="potion" type="ItemType" />
                <xs:element name="revive" type="ItemType" />
                <xs:element name="pokeball" type="ItemType" />
            </xs:choice>
            <xs:element name="region" type="RegionType"/>
            <xs:element name="team">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="pokemon" type="TrainerPokemon" minOccurs="1" maxOccurs="6" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:group name="PokemonElements">
        <xs:sequence>
            <xs:element name="name" type="PokemonName" minOccurs="1" maxOccurs="1" />
            <xs:element name="type" type="PokemonType" minOccurs="1" maxOccurs="2" />
            <xs:element name="stats" type="stats:PokemonStats" minOccurs="1" maxOccurs="1" />
        </xs:sequence>
    </xs:group>

    <xs:complexType name="Pokemon">
        <xs:group ref="PokemonElements" />
        <xs:attribute name="id" use="required" />
    </xs:complexType>

    <xs:complexType name="TrainerPokemon">
        <xs:attributeGroup ref="PokemonAttributes"/>
        <xs:complexContent>
            <xs:extension base="Pokemon">
                <xs:sequence>
                    <xs:element name="nickname" maxOccurs="1" minOccurs="0" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="PokemonName">
        <xs:annotation>
            <xs:documentation>The name of the Pokemon</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="^[a-zA-Z\-]*$"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== jean-andre-gauthier/xmlschema.js/test/pokemons/xml/bulbasaur.xml
<trainer xmlns="https://paulwardrip.github.io/xmlschema.js/demo/pokemon"
         xmlns:s="https://paulwardrip.github.io/xmlschema.js/demo/pokemon/stats"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://paulwardrip.github.io/xmlschema.js/demo/pokemon
            pokemon.xsd">

    <pokeball inventory="2" />
    <potion inventory="1" />
    <revive inventory="3" />

    <team>
        <!-- valid pokemon -->
        <pokemon id="1" level="4" hp="100">
            <name>Bulbasaur</name>
            <type>poison</type>
            <type>grass</type>
            <stats>
                <s:hp></s:hp>
                <s:defense></s:defense>
                <s:sp-defense></s:sp-defense>
                <s:attack></s:attack>
                <s:sp-attack></s:sp-attack>
            </stats>
        </pokemon>

        <!-- invalid pokemon -->
        <pokemon id="1">
            <name>Bulbasaur1</name>
            <type>poison</type>
            <type>grass</type>
            <type>watur</type>
            <stats>
            </stats>
        </pokemon>
    </team>
</trainer>
